Update cicd.yml

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -58,18 +58,18 @@ jobs:
           sleep 10
 
       # Health check - wait for app
-      - name: Wait for FastAPI to be ready
-        run: |
-          for i in {1..15}; do
-            if curl -sSf http://localhost:8000/docs >/dev/null; then
-              echo "APP IS UP"
-              exit 0
-            fi
-            echo "Waiting for FastAPI..."
-            sleep 5
-          done
-          echo "App failed to start"
-          exit 1
+      # - name: Wait for FastAPI to be ready
+      #   run: |
+      #     for i in {1..15}; do
+      #       if curl -sSf http://localhost:8000/docs >/dev/null; then
+      #         echo "APP IS UP"
+      #         exit 0
+      #       fi
+      #       echo "Waiting for FastAPI..."
+      #       sleep 5
+      #     done
+      #     echo "App failed to start"
+      #     exit 1
 
       # Run OWASP ZAP Baseline Scan
       - name: Run OWASP ZAP Baseline Scan
